# https://swagger.io/docs/specification/about/
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md

openapi: 3.0.3

info:
  title: "Example API"
  description: This is just an example API
  version: 1.0.0
  contact:
    email: roman@ozana.cz

servers:
  - url: https://ozana.cz/
    description: Example

paths:
  /user:
    get:
      operationId: Get User
      description: Retrieve User
      security:
        - ApiKey: [ ]
      tags:
        - User
      responses:
        200:
          description: Retrieve User object
          content:
            application/json:
              schema:
                $ref: schemas/User.yaml
  /articles:
    get:
      operationId: Get Article
      description: Retrieve Article
      security:
        - ApiKey: [ ]
      tags:
        - Article
      responses:
        200:
          description: Retrieve Article object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: schemas/Article.yaml
components:
  securitySchemes:
    ApiKey:
      description: This is just ApiKey
      type: apiKey
      name: apiKey
      in: query